// Generated by CoffeeScript 1.12.6
(function() {
  var number, opposite, square;

  number = 142;

  opposite = true;

  if (opposite) {
    number = -42;
  }

  square = function(x) {
    return x * x;
  };

}).call(this);
